### ISSUE TITLE
Add PUT, POST, DELETE apis

### ISSUE THREAD

**Issue by dmcnulla** [stevenjackson/pinch_hitter#1]
Steve,

Could you add put, post, and delete apis to pinch_hitter? For delete, I'd like to store a message to reply, like with get. For put and post, I'd like to be able to remove the sent message from the queue if it gets added. I'll add some cukes later.

Thanks, Dave

**Comment by stevenjackson** [comment]
Hi Dave,

Just getting around to this, but I had another request for adding the ability to check POSTs made by the application.  My thought is to add a method like [`received_requests`](https://github.com/stevenjackson/pinch_hitter/blob/master/lib/pinch_hitter.rb#L37,L40) that will return all the requests made against that endpoint.  My thought is you could use this to verify anything with a body in the request (PUT, POST).  I'm also thinking I can alias PUT and DELETE so it works just like GET and POST work now (return the primed response).

**Comment by dmcnulla** [comment]
Those sound like good ideas. Also checking the headers is good -I can't remember if that is already incorporated. Thanks for looking at this! 

Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by stevenjackson** [comment]
This has been pushed as v0.4.  PUT and DELETE (and PATCH) now work like GET and POST.  Additionally you can pull any requests your application has sent to pinch_hitter via the `request_log` or `received_messages` methods.
