### ISSUE TITLE
Unprimed endpoints return a success response

### ISSUE THREAD

**Issue by nwallace** [stevenjackson/pinch_hitter#9]
Hey Steve, hope life is treating you well! :smile:  We need something like PinchHitter for mocking out some interactions with our payment processor, and there are a few features I'd like to add.

First up is this one! If you request an endpoint that hasn't been stored, right now it returns a blank 200 response. For our purposes, it would be better for it to return a 404. This might be similar to #7 (it could be implemented via some such mechanism), but I think this should be the default behavior, and then #7 could be used to get back the old behavior or any other desired behavior.

Whatdya think?

**Comment by stevenjackson** [comment]
404s as the default makes sense to me.  Definitely better than a 200 and a log message :)

**Comment by nwallace** [comment]
Cool, I'll probably start digging into this tomorrow :heart:
